"""数据源类型元数据 — 前端动态表单 + 对接引导（V2.5 真实对接版）

每个类型定义完整配置字段（真实对接接口维度），前端按 fields 渲染表单：
  type: text | password | number | select | textarea
  required: 必填；placeholder: 输入示例；help: 引导文案；options: select 选项

guide: 类型级对接指引（展示在表单顶部，说明连接要求/权限/前置条件）
"""

TYPE_META = {
    "API": {
        "label": "API 告警平台",
        "guide": "对接厂商/自研安全运营平台的告警查询 REST API。要求：接口可达、支持按时间窗口过滤、账号具备告警查询权限。",
        "fields": [
            {"key": "endpoint", "label": "接口地址", "type": "text", "required": True,
             "placeholder": "https://10.0.1.5:8443/api/v1/alerts",
             "help": "告警查询接口，需支持分页与时间过滤参数"},
            {"key": "auth_type", "label": "认证方式", "type": "select", "required": True,
             "options": [{"label": "Bearer Token", "value": "bearer"},
                         {"label": "API Key (Header)", "value": "apikey"},
                         {"label": "基础认证", "value": "basic"},
                         {"label": "无认证", "value": "none"}],
             "help": "平台支持的认证方式，见平台 API 文档"},
            {"key": "token", "label": "Token / API Key", "type": "password",
             "placeholder": "eyJhbGciOi... 或 xxxxxxxx",
             "help": "auth_type=bearer 放 Bearer Token；apikey 放 API Key（默认放 X-API-Key 头）"},
            {"key": "username", "label": "用户名", "type": "text",
             "placeholder": "api_user", "help": "auth_type=basic 时必填"},
            {"key": "password", "label": "密码", "type": "password",
             "placeholder": "********", "help": "auth_type=basic 时必填"},
            {"key": "time_field", "label": "时间字段名", "type": "text",
             "placeholder": "time", "help": "告警时间字段名（用于窗口过滤）"},
            {"key": "time_format", "label": "时间格式", "type": "text",
             "placeholder": "%Y-%m-%d %H:%M:%S", "help": "ISO8601 或 strftime 格式"},
            {"key": "page_size", "label": "分页大小", "type": "number",
             "placeholder": "500", "help": "单页条数，默认 500"},
            {"key": "extra_params", "label": "附加查询参数", "type": "textarea",
             "placeholder": '{"severity": "HIGH"}',
             "help": "固定附加参数（JSON），会合并进每次请求"},
        ],
    },
    "ES": {
        "label": "Elasticsearch 日志检索",
        "guide": "对接 ES 集群检索安全日志/告警。要求：集群可达、索引存在、账号具备该索引 read 权限。",
        "fields": [
            {"key": "es_url", "label": "集群地址", "type": "text", "required": True,
             "placeholder": "http://10.0.1.2:9200",
             "help": "ES 集群 HTTP 地址，支持 https"},
            {"key": "auth_type", "label": "认证方式", "type": "select", "required": True,
             "options": [{"label": "基础认证", "value": "basic"},
                         {"label": "API Key", "value": "apikey"},
                         {"label": "无认证", "value": "none"}],
             "help": "ES 安全特性开启时的认证方式"},
            {"key": "username", "label": "用户名", "type": "text",
             "placeholder": "elastic", "help": "auth_type=basic 时必填"},
            {"key": "password", "label": "密码", "type": "password",
             "placeholder": "********", "help": "auth_type=basic 时必填"},
            {"key": "api_key", "label": "API Key", "type": "password",
             "placeholder": "base64:xxxx", "help": "auth_type=apikey 时必填（Authorization: ApiKey）"},
            {"key": "index_pattern", "label": "索引模式", "type": "text", "required": True,
             "placeholder": "security-alerts-*",
             "help": "索引或通配符模式，如 security-alerts-2026.08.*"},
            {"key": "time_field", "label": "时间字段", "type": "text",
             "placeholder": "@timestamp",
             "help": "文档时间字段（用于窗口 range 查询）"},
            {"key": "query_dsl", "label": "附加过滤 DSL", "type": "textarea",
             "placeholder": '{"term": {"event.type": "alert"}}',
             "help": "附加 bool 过滤条件（JSON），会与时间窗口 AND 合并"},
            {"key": "size", "label": "单批条数", "type": "number",
             "placeholder": "500", "help": "每次 search 返回条数，默认 500"},
        ],
    },
    "DB": {
        "label": "漏洞台账数据库",
        "guide": "对接 MySQL 等关系库中的漏洞/资产台账。要求：库可达、账号具备目标表 SELECT 权限。",
        "fields": [
            {"key": "db_url", "label": "连接串", "type": "text", "required": True,
             "placeholder": "mysql+pymysql://user:pass@10.0.1.6:3306/vuln_db",
             "help": "SQLAlchemy 连接串，支持 mysql+pymysql:// / sqlite:/// 等"},
            {"key": "table", "label": "表名", "type": "text", "required": True,
             "placeholder": "vuln_ledger", "help": "漏洞/资产台账表名"},
            {"key": "time_field", "label": "时间字段", "type": "text",
             "placeholder": "discover_time",
             "help": "发现时间字段（用于窗口过滤）"},
            {"key": "time_format", "label": "时间格式", "type": "text",
             "placeholder": "%Y-%m-%d %H:%M:%S", "help": "时间字段的存储格式"},
            {"key": "extra_fields", "label": "字段映射", "type": "textarea",
             "placeholder": '{"vuln_name": "name", "cvss": "cvss_score"}',
             "help": "可选：台账列 → 事件 extra 字段映射（JSON）"},
        ],
    },
    "SYSLOG": {
        "label": "Syslog 日志文件",
        "guide": "读取采集落盘的 syslog 日志文件。要求：文件存在、服务账号可读。",
        "fields": [
            {"key": "file_path", "label": "日志文件路径", "type": "text", "required": True,
             "placeholder": "/data/logs/firewall/syslog.log"},
            {"key": "encoding", "label": "编码", "type": "text",
             "placeholder": "utf-8", "help": "文件编码，默认 utf-8"},
            {"key": "time_format", "label": "时间格式", "type": "text",
             "placeholder": "%b %d %H:%M:%S", "help": "日志行内时间格式"},
        ],
    },
    "EXCEL": {
        "label": "Excel 威胁情报台账",
        "guide": "读取 xlsx 格式威胁情报台账。要求：文件存在、格式符合模板（含时间列）。",
        "fields": [
            {"key": "file_path", "label": "xlsx 文件路径", "type": "text", "required": True,
             "placeholder": "/data/intel/threat_ledger.xlsx"},
            {"key": "time_column", "label": "时间列名", "type": "text",
             "placeholder": "create_time", "help": "时间列，用于窗口过滤"},
        ],
    },
    "INTEL": {
        "label": "威胁情报 IOC 源",
        "guide": "读取 IOC 情报文件（jsonl/文本，每行一条）。要求：文件存在。",
        "fields": [
            {"key": "file_path", "label": "IOC 文件路径", "type": "text", "required": True,
             "placeholder": "/data/intel/iocs.jsonl"},
            {"key": "ioc_type_filter", "label": "IOC 类型过滤", "type": "select",
             "options": [{"label": "全部", "value": "all"},
                         {"label": "仅 IP", "value": "ip"},
                         {"label": "仅域名", "value": "domain"},
                         {"label": "仅哈希", "value": "hash"}],
             "help": "可选：只保留指定类型 IOC"},
        ],
    },
    "HISTORY": {
        "label": "历史报告源（环比）",
        "guide": "读取本地历史报告用于环比对比。无额外配置。",
        "fields": [
            {"key": "cycle", "label": "周期（可选）", "type": "text",
             "placeholder": "MONTHLY", "help": "限定读取某周期历史报告，留空自动"},
        ],
    },
}
